### PR TITLE
API data update from `PokeAPI/pokeapi#568`

### PR DESCRIPTION
**Pull request by pokeapi-machine-user**
Incoming data generated by [PokeAPI/pokeapi](https://github.com/PokeAPI/pokeapi)'s CircleCI worker since Pull Request [#568](https://github.com/PokeAPI/pokeapi/pull/568) was merged into the `master` branch. <br><br> The new data was generated using a copy of [PokeAPI/pokeapi](https://github.com/PokeAPI/pokeapi/commits/master) repository when the `HEAD` was pointing to `4f4d124148a8d693cb81751b30c37d792f5815fe`. <br><br> This Pull Request should have been deployed in our [staging environment](https://staging.pokeapi.co/api/v2/), check [here](https://app.circleci.com/pipelines/github/PokeAPI/deploy) for the lastest build timestamp and status code.

### CODE REVIEW

**Review by Naramsim — APPROVED** [review]

**Comment by Naramsim** [comment]
Ok, I reviewed basically all the files 😫 

We have only two regressions, for two forms: 10086 and 10132.

https://staging.pokeapi.co/api/v2/pokemon-form/10086
https://pokeapi.co/api/v2/pokemon-form/10086

https://staging.pokeapi.co/api/v2/pokemon-form/10132
https://pokeapi.co/api/v2/pokemon-form/10132

@C-Garza could it be that their `is_default` is wrongly set? 

Anyway, @C-Garza and @zacbullard, I'm going to merge this even if we have those two small regressions.

**Comment by C-Garza** [comment]
Oh wow, nice job @Naramsim! 😮

Yeah I noticed that those two had a `is_default` value of 0 when scrolling down the [pokemon_forms.csv](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_forms.csv#L667).

I think those values are correct, I'm just not sure why Veekun has the pokemon id is not set to the default one. Maybe it was and they changed the data at some point? I'm not sure. 

So I went and did some digging and found out that those were originally the `is_default` forms but were changed in [in this commit over at Veekun](https://github.com/veekun/pokedex/commit/0b81ea0c795f172c3406c0133ad84929d51186f9#diff-1a83d06db25989069895dc345a0a141b1fbc9843b48dabdb52d5de50b8048e74). I think the `is_default` values are correct, but do you think it's a mistake that they didn't swap the correct default form over when they made this change?

**Comment by zacbullard** [comment]
Hi All, thanks for all the good work and review!

So those two pokemon are purely aesthetic "forms" as per the following discussion. They should not be defaults.

https://github.com/PokeAPI/pokeapi/issues/401

**Comment by Naramsim** [comment]
> but do you think it's a mistake that they didn't swap the correct default form over when they made this change?

To be honest, I'm not understanding very well this part, maybe it's because the last pokemon game I played was Emerald... :) 

To my understanding, in our API we have [species](https://pokeapi.co/api/v2/pokemon-species/493/), which can have many varieties. These varieties are [pokemon](https://pokeapi.co/api/v2/pokemon/493/) and these pokemon can have different [forms](https://pokeapi.co/api/v2/pokemon-form/10041/). A variety can be a default for a species, and a form can be the default for a pokemon.

Now I don't understand if these so-called varieties really exist in pokemon games or if was a `hack` on our side to better describe the situation. 

In the end, I cannot answer your question. 

Then @zacbullard comes in with his comment and tells that there are forms and purely aesthetic "forms", as the situation wasn't already enough foggy. Hahahha 

I don't know, we can put them back with the `is_default` equal to 0. You two decide.

I'm merging

**Comment by zacbullard** [comment]
Hey Narasim,

Sorry, I didn't mean to imply 'there are forms and purely aesthetic "forms"', I was saying that _all_ form differences are purely aesthetic differences as per the definition of form used by PokeAPI. And that 10086 and 10132 are not default. 

Vivillion (which 10086 belongs to) is actually mentioned as an example in that discussion I linked. Vivillion (https://pokeapi.co/api/v2/pokemon-form/666) defaults to using the  ["Meadow" version](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/666-meadow.png) of the wings, while https://pokeapi.co/api/v2/pokemon-form/10086 is a different form with ["Icy Meadow" wings](https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/666-icy-snow.png). Besides the different colors of wings, mechanically these pokemon are exactly the same in every way.

Same thing for 716 and 10132.

The pokemon games don't make this official distinction between "varieties", "forms", etc. but from an API perspective it's pretty smart you guys are doing this, since the varieties might have different information such as moves, stats, etc. (like the mega evolutions), while the forms are mostly just different in .png files and subtitles.

As for Veekun and why they switched around the `is_default` tags in the past, I don't know why they did so, it was probably either a purely personal preference or possible error. There's no mechanical reason why "Meadow" Vivillion should be "more default" than "Icy Meadow" Vivillion as far as I know. Someone made a choice long ago and that's that.

Regardless, 10086 and 10132 are not the the defaults for and 666 and 716, so the current `is_current` is fine.

**Comment by Naramsim** [comment]
Yeah yeah, I was kidding by the way :)

**Comment by C-Garza** [comment]
I think those `is_default` values are correct, it's just that when they changed them they didn't swap it out for the correct form as well which is why they both look like outliers. I think the mistake here is that they don't have the default forms `vivillon-icy-snow` as `666` and `xerneas-neutral` as `716`. In my opinion, all the normal pokemon id's should be the default form, but for those two, they are not.

And Emerald was a great game, the last one I seriously played was SoulSilver 😛.

**Comment by zacbullard** [comment]
Hm, I thought that 666 and 716 were the defaults when I looked at them (and thought that through the previous discussions), but currently it's actually 10086 and 10132. I completely agree with @C-Garza , all the normal pokemon ids should be the defaults, not the 10xxx ids.

 As for myself, I played the original Red, took a 23 year hiatus, and then beat Sword :)

**Pull request merged**
