### PR TITLE
API data update from `PokeAPI/pokeapi#512`

### PR DESCRIPTION
**Pull request by pokeapi-machine-user**
Incoming data generated by [PokeAPI/pokeapi](https://github.com/PokeAPI/pokeapi)'s CircleCI worker since Pull Request [#512](https://github.com/PokeAPI/pokeapi/pull/512) was merged into the `master` branch. <br><br> The new data was generated using a copy of [PokeAPI/pokeapi](https://github.com/PokeAPI/pokeapi/commits/master) repository when the `HEAD` was pointing to `6f79b479059196b1ba0a4fa4b46963795e9bae47`. <br><br> This Pull Request should have been deployed in our [staging environment](https://staging.pokeapi.co/api/v2/), check [here](https://app.circleci.com/pipelines/github/PokeAPI/deploy) for the lastest build timestamp and status code.

### CODE REVIEW

**Comment by Naramsim** [comment]
Magi

Can you check everything works as expected, @C-Garza?

**Comment by C-Garza** [comment]
Seems like it's working for me @Naramsim. Should I work on adding the next generation then?

**Comment by Naramsim** [comment]
Yeah, I would do a PR at a time. Like one generation/`other` sprites each PR. We can start with the `official-artwork` which is already present in the `PokeAPI/sprites` repo. Maybe we can complete first the `versions` part of the sprites.

**Comment by C-Garza** [comment]
So you're saying to go back and forth between generation/other in the PR's, starting with `official-artwork`?

**Comment by Naramsim** [comment]
Let's do:
- PR towards `Pokeapi/sprites` generation-ii
- PR towards `Pokeapi/sprites` generation-iii
- PR towards `Pokeapi/sprites` generation-iv
- PR towards `Pokeapi/sprites` generation-v
- PR towards `Pokeapi/sprites` generation-vi
- PR towards `Pokeapi/sprites` generation-vii
- PR towards `Pokeapi/pokeapi` add the above generations and official-artwork to the API.

**Pull request merged**
