### PR TITLE
Setting is_legendary flag for Ruinous Quartet as true

### PR DESCRIPTION
**Pull request by yor-so**
Fixing issue 157 `https://github.com/PokeAPI/pokedex/issues/157`

### CODE REVIEW

**Review by misterhay — COMMENTED** [review]
Looks great, thanks for doing this

**Comment by Naramsim** [comment]
Hi, sorry, this is not the right place. This data is generated by a script.

**Comment by Naramsim** [comment]
We have CSV files that have to be modified.

**Comment by Naramsim** [comment]
https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_species.csv

**Pull request closed without merging**
